# Generated by Django 4.2.7 on 2023-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
